document.addEventListener('DOMContentLoaded', () => {
    // 1. Fetch the data generated by the Python script
    fetch('data_web.json')
        .then(response => response.json())
        .then(data => {
            // Update Strategy Name and Date Headers
            document.title = `${data.StrategyName} | ReplicAlgo`;
            const titleElement = document.querySelector('h1') || document.querySelector('.strategy-title');
            if (titleElement) titleElement.textContent = data.StrategyName;

            // Fix the "undefined" labels
            const monthLabels = document.querySelectorAll('.month-label');
            monthLabels.forEach(label => {
                label.textContent = data.MesActual || "Sin Fecha";
            });

            // 2. Populate Orders Table (Ordenes del Mes)
            const ordersBody = document.getElementById('orders-body');
            if (ordersBody && data.Ordenes) {
                ordersBody.innerHTML = data.Ordenes.map(order => `
                    <tr>
                        <td class="p-3">${order.Accion}</td>
                        <td class="p-3">${order.Simbolo}</td>
                        <td class="p-3">${order.Nombre}</td>
                        <td class="p-3">${order.Instruccion}</td>
                        <td class="p-3">${order.MGC}</td>
                    </tr>
                `).join('');
            }

            // 3. Populate Portfolio Table (Portafolio Actual)
            const portfolioBody = document.getElementById('portfolio-body');
            if (portfolioBody && data.Portafolio) {
                portfolioBody.innerHTML = data.Portafolio.map(item => `
                    <tr>
                        <td class="p-3">${item.Simbolo}</td>
                        <td class="p-3">${item.Nombre}</td>
                        <td class="p-3">${item.Peso}</td>
                        <td class="p-3">${item.Estado}</td>
                        <td class="p-3">${item.MGC}</td>
                    </tr>
                `).join('');
            }

            // 4. Populate Performance Summary
            if (data.Historico && data.Historico.resumen) {
                document.getElementById('bench-return').textContent = data.Historico.resumen.Benchmark;
                document.getElementById('strat-return').textContent = data.Historico.resumen.Strategy;
            }

            // 5. Populate Annual Table (Rendimiento Anual Detallado)
            const annualBody = document.getElementById('annual-body');
            if (annualBody && data.Historico.tabla_anual) {
                annualBody.innerHTML = data.Historico.tabla_anual.map(row => `
                    <tr>
                        <td class="p-2">${row.Año}</td>
                        <td class="p-2">${row.Retorno}</td>
                        <td class="p-2 text-red-400">${row.MaxPerdida}</td>
                    </tr>
                `).join('');
            }
        })
        .catch(err => console.error("Error loading strategy data:", err));
});